# App Env
GO_APP=go
RUNNER_APP=nodemon
MIGRATE_APP=migrate
LINT_APP=golangci-lint

SERVER_FILE=cmd/server/main.go
BINARY_FILE=main

MIGRATE_FOLDER=./database/migration
MIGRATE_DB_CONN=postgresql://<username>:<password>@127.0.0.1:5432/<schema>?sslmode=disable

env:
	cp example.env .env
deps:
	$(GO_APP) mod tidy
run:
	$(GO_APP) run $(SERVER_FILE)
build:
	$(GO_APP) build -o $(BINARY_FILE) $(SERVER_FILE)
swag:
	swag init --generalInfo $(SERVER_FILE)

lint:
	@echo -e "==> start linting..."
	$(LINT_APP) run --fix

migrate.create:
	$(MIGRATE_APP) create -ext sql -dir $(MIGRATE_FOLDER) $(name)
migrate.up:
	$(MIGRATE_APP) -path $(MIGRATE_FOLDER) -database $(MIGRATE_DB_CONN) --verbose up
migrate.down:
	$(MIGRATE_APP) -path $(MIGRATE_FOLDER) -database $(MIGRATE_DB_CONN) --verbose down
migrate.fix:
	$(MIGRATE_APP) -path $(MIGRATE_FOLDER) -database $(MIGRATE_DB_CONN) force $(version)
